easy_admin:
    entities:
           User:
            class: App\Entity\User
           Expense:
            class: App\Entity\Expense
           Category:
            class: App\Entity\Category
            list:
              fields:
                - { property : 'id'}
                - { property : 'content'}